parameters:
    nibynool_fitbit_interface.key: ''
    nibynool_fitbit_interface.secret: ''
    nibynool_fitbit_interface.callback: ''
    nibynool_fitbit_interface.configuration: []
services:
    nibynool.fitbit.interface:
        class:     Nibynool\FitbitInterfaceBundle\Fitbit\ApiGatewayFactory
        arguments:
            - %nibynool_fitbit_interface.key%
            - %nibynool_fitbit_interface.secret%
            - %nibynool_fitbit_interface.callback%
            - %nibynool_fitbit_interface.configuration%
            - @router